<a href="https://colab.research.google.com/github/aazadvoice/Python_Journey/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr=np.array([10,20,30,40,50])

In [ ]:
arr.shape

(5,)

In [ ]:
arr.size

5

In [ ]:
print(arr)

[10 20 30 40 50]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
import numpy

In [ ]:
arr1=numpy.array([2.3,4.5,6.7])

In [ ]:
arr1

array([2.3, 4.5, 6.7])

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
arr1.ndim

1

In [ ]:
from numpy import *

In [ ]:
arr3=array([1,1,1,1,1])

In [ ]:
arr3

array([1, 1, 1, 1, 1])

In [ ]:
np.__version__

'2.2.6'

In [ ]:
ar1=np.array([(10,20,30),(40,50,60),(5,7,9)])

In [ ]:
ar1

array([[10, 20, 30],
       [40, 50, 60],
       [ 5,  7,  9]])

In [ ]:
ar1.ndim

2

In [ ]:
ar1.shape

(3, 3)

In [ ]:
ar1.size

9

In [ ]:
ar1.data

In [ ]:
ar1.dtype

dtype('int64')

In [ ]:
ar1.size

9

In [ ]:
list1=[100,200,300,400,500]

In [ ]:
#creating an array from a list
arr1=np.array(list1)
arr1

array([100, 200, 300, 400, 500])

In [ ]:
print(arr1)

[100 200 300 400 500]


In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
t1=(100,200,300,400,500)

In [ ]:
#creating an array from a tuple
arr1=np.array(t1)
arr1

array([100, 200, 300, 400, 500])

In [ ]:
str1=np.array(["aaa","bbb","ccc"])

In [ ]:
str1

array(['aaa', 'bbb', 'ccc'], dtype='<U3')

In [ ]:
str1[0]

np.str_('aaa')

In [ ]:
str1="good morning everyone"

In [ ]:
arr1=np.array(str1.split())

In [ ]:
arr1

array(['good', 'morning', 'everyone'], dtype='<U8')

In [ ]:
arr1[2]

'everyone'

In [ ]:
data=np.array([[180,70],[155,78],[110,56],[180,80],[158,90]])

In [ ]:
data

array([[180,  70],
       [155,  78],
       [110,  56],
       [180,  80],
       [158,  90]])

In [ ]:
data.ndim

NameError: name 'data' is not defined

In [ ]:
arr=np.array([10,20,30,40,50])

In [ ]:
arr.ndim

1

In [ ]:
arr=np.array([10,20,30,40,50,60,70,80,90,100]).reshape(2,-1)

In [ ]:
arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [ ]:
arr.shape


(2, 5)

In [ ]:
arr.size

10

In [ ]:
arr[0]

array([10, 20, 30, 40, 50])

In [ ]:
arr[1]

array([ 60,  70,  80,  90, 100])

In [ ]:
arr[0,1]

np.int64(20)

In [ ]:
arr[1,6]

IndexError: index 6 is out of bounds for axis 1 with size 5

In [ ]:
arr[1]

array([ 60,  70,  80,  90, 100])

In [ ]:
arr[2,0]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [ ]:
a=np.array([arr])

In [ ]:
a

array([[[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100]]])

In [ ]:
a=np.arange(50)

In [ ]:
a

array([[[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100]]])

In [ ]:
a=np.arange(50).reshape(10,5)

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [ ]:
a[2:5]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
a[2:6,3]

array([13, 18, 23, 28])

In [ ]:
a[2:5,1:4]

array([[11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [ ]:
a[:,4]

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49])

In [ ]:
a[:,-1]

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49])

In [ ]:
a[6:10,2:5]

array([[32, 33, 34],
       [37, 38, 39],
       [42, 43, 44],
       [47, 48, 49]])

In [ ]:
a=np.arange(50).reshape(10,-1)

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
a=np.arange(10,50).reshape(5,-1)

In [ ]:
a

array([[10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
import numpy as np
a=np.arange(10,50,2)

In [ ]:
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [ ]:
a.size

20

In [ ]:
a.min()

10

In [ ]:
a.max()

48

In [ ]:
a.sum()

580

In [ ]:
a.mean()

np.float64(29.0)

In [ ]:
a=np.arange(10,50,2).reshape(-1,5)

In [ ]:
a

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [ ]:
a

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [ ]:
a.min()
a.mean()
a.max()


np.int64(49)

In [ ]:
a.max(axis=1)

array([16, 24, 32, 40, 48])

In [ ]:
a.max(axis=0)

array([42, 44, 46, 48])

In [ ]:
np.array([0,0,0,0,0])

array([0, 0, 0, 0, 0])

In [ ]:
np.array([1,1,1,1,1])

array([1, 1, 1, 1, 1])

In [ ]:
z=np.zeros(10,dtype=int)

In [ ]:
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
z[4]=400
z

array([  0,   0,   0,   0, 400,   0,   0,   0,   0,   0])

In [ ]:
z=np.zeros(10).reshape(5,2)

In [ ]:
z

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
z=np.zeros(10)

In [ ]:
z.dtype

dtype('float64')

In [ ]:
z[2]=200

In [ ]:
z[5]=500

In [ ]:
z

array([  0.,   0., 200.,   0.,   0., 500.,   0.,   0.,   0.,   0.])

In [ ]:
z[3]=400

In [ ]:
z.flags.writeable=False

In [ ]:
z[1]=100

ValueError: assignment destination is read-only

In [ ]:
z.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [ ]:
z[1]=100

In [ ]:
z

array([  0., 100., 200., 400.,   0., 500.,   0.,   0.,   0.,   0.])

In [ ]:
# prints the indices where the value is not a zero
nz=np.nonzero([10,20,0,30,40,0,50,0,60])

In [ ]:
nz


(array([0, 1, 3, 4, 6, 8]),)

In [ ]:
#set the datatype as integer
z=np.zeros(10,dtype="int")

In [ ]:
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr=np.array([3,5,7,9],dtype="str")


In [ ]:
arr

array(['3', '5', '7', '9'], dtype='<U1')

In [ ]:
np.full((3,3),False,dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.full((3,3),True,dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((9,3),False,dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.full((3,3),False,dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
#create an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Arithmatic operations

In [ ]:
a=np.array([10,11,12,13,14,15])

In [ ]:
print(a+5)

[15 16 17 18 19 20]


In [ ]:
print(a-5)

[ 5  6  7  8  9 10]


In [ ]:
print(a*2)

[20 22 24 26 28 30]


In [ ]:
print(a**2)

[100 121 144 169 196 225]


In [ ]:
a

array([10, 11, 12, 13, 14, 15])

In [ ]:
a=a**2

In [ ]:
a

array([100, 121, 144, 169, 196, 225])

In [ ]:
arr=np.arange(27)

In [ ]:
arr=np.arange(27).reshape(9,3)

In [ ]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
arr=np.arange(27).reshape(3,3,3)

In [ ]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
arr.ndim

3

In [ ]:
arr.ndim

3

In [ ]:
arr.shape

(3, 3, 3)

In [ ]:
#create a 2d array with np.zeros
np.zeros(10).reshape(5,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
x=np.zeros((4,5,6))

In [ ]:
x

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [ ]:
x.size
x.ndim

3

In [ ]:
x=np.random.random((3,3))

In [ ]:
x

array([[0.99444452, 0.16023916, 0.65311033],
       [0.85543093, 0.87531093, 0.41285222],
       [0.58867796, 0.43486533, 0.79087053]])

In [ ]:
x=np.random.random((3,3,3))

In [ ]:
x

array([[[0.99072028, 0.96451245, 0.41128796],
        [0.71287946, 0.28819441, 0.52514584],
        [0.46648871, 0.70791178, 0.68154657]],

       [[0.0332555 , 0.3635726 , 0.9678791 ],
        [0.85937454, 0.68518561, 0.82738208],
        [0.23857255, 0.23956032, 0.33758355]],

       [[0.52054639, 0.655007  , 0.86235685],
        [0.49148263, 0.36655489, 0.01284555],
        [0.47437328, 0.99296556, 0.1895131 ]]])

In [ ]:
x=np.random.random((10,10))

In [ ]:
x

array([[0.15786723, 0.97432961, 0.96091582, 0.98407702, 0.22387089,
        0.78585987, 0.78022763, 0.80330784, 0.2038547 , 0.87425804],
       [0.55618954, 0.82351369, 0.86887996, 0.20469083, 0.03538603,
        0.98187816, 0.29717278, 0.43386128, 0.73191065, 0.24776907],
       [0.25459809, 0.44308463, 0.16952011, 0.6572918 , 0.52111198,
        0.27731621, 0.92968813, 0.04798278, 0.06478553, 0.28354421],
       [0.64331798, 0.59331261, 0.3961993 , 0.55818872, 0.27988553,
        0.33586571, 0.01172448, 0.16942316, 0.10784979, 0.99801254],
       [0.71850524, 0.53886922, 0.61641672, 0.58564941, 0.42419716,
        0.89734496, 0.34603565, 0.94458168, 0.64520464, 0.79638361],
       [0.6987467 , 0.40348879, 0.03146655, 0.11678918, 0.57125571,
        0.45166545, 0.04014223, 0.0898929 , 0.28042848, 0.0097352 ],
       [0.59327303, 0.08124984, 0.76787522, 0.43497829, 0.17464202,
        0.97925037, 0.95470094, 0.09361497, 0.03351641, 0.9281689 ],
       [0.13202228, 0.22742332, 0.8421944

In [ ]:
xmin,xmax=x.min(),z.max()

In [ ]:
xmin

0.0014871437319621261

In [ ]:
xmax

0

In [ ]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
#print all odd numbers
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [ ]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
#replace all odd numbers with 100
arr[arr%2==1]=100

In [ ]:
arr

array([  0, 100,   2, 100,   4, 100,   6, 100,   8, 100])

In [ ]:
arr2=arr.copy()

In [ ]:
arr2

array([  0, 100,   2, 100,   4, 100,   6, 100,   8, 100])

In [ ]:
import numpy as np
a1=np.array([1,3,5])
b1=np.array([2,4,6])

In [ ]:
a1

array([1, 3, 5])

In [ ]:
b1

array([2, 4, 6])

In [ ]:
c1

NameError: name 'c1' is not defined

In [ ]:
c1=np.concatenate((a1,b1))

In [ ]:
c1

array([1, 3, 5, 2, 4, 6])

In [ ]:
a1=np.array([[1,2,3],[4,5,6]])
b1=np.array([[7,8,9],[10,11,12]])

In [ ]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b1

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
c1=np.concatenate((a1,b1))

In [ ]:
c1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
a1=np.array([1,2,3,5,9,6,8])
b1=np.array([2,2,4,6,5])

In [ ]:
#find the common values in a1 and b1
np.intersect1d(a1,b1)

array([2, 5, 6])

In [ ]:
np.union1d(a1,b1)

array([1, 2, 3, 4, 5, 6, 8, 9])

In [ ]:
np.setdiff1d(a1,b1)

array([1, 3, 8, 9])

In [ ]:
np.setdiff1d(b1,a1)

array([4])